/**
 * Applies the generated project-schema SQL against PostgreSQL at runtime.
 *
 * `pg` rather than Prisma raw: the script generated by `./project-schema` sets
 * `search_path`, which is session-scoped, so every statement must run on one
 * connection in one call. `pg`'s `Client.query(text)` uses the simple-query
 * protocol and runs the whole script; Prisma pools connections and cannot run
 * multi-statement SQL.
 *
 * Resolved as part of Task 1.2b — see docs/14-decisions-needed.md.
 */
import { Client } from 'pg';

import { assertValidSchemaName, generateProjectSql } from './project-schema';

/**
 * `DATABASE_URL` with the Prisma-only `schema=` query param removed.
 *
 * The executor connects at database level: `CREATE SCHEMA "<name>"` names the
 * schema explicitly, so no schema routing is wanted — and leaving `schema=public`
 * in place would be misleading since it only names a search path, not a target.
 * Other params (`sslmode` etc.) are preserved.
 */
function databaseUrl(): string {
  const base = process.env.DATABASE_URL;
  if (!base) throw new Error('DATABASE_URL is not set');

  const url = new URL(base);
  url.searchParams.delete('schema');
  return url.toString();
}

/**
 * Create one project schema (and the tables the project template defines).
 *
 * Atomic: the whole script runs inside an explicit transaction, and Postgres
 * DDL is transactional, so a mid-script failure rolls everything back — never
 * leaving a half-created schema.
 */
export async function createProjectSchema(schemaName: string): Promise<void> {
  assertValidSchemaName(schemaName);
  const sql = generateProjectSql(schemaName);

  const client = new Client({ connectionString: databaseUrl() });
  try {
    await client.connect();
    await client.query('BEGIN');
    await client.query(sql);
    await client.query('COMMIT');
  } catch (error) {
    // The connection may already be dead; swallow the rollback error and
    // rethrow the original.
    await client.query('ROLLBACK').catch(() => {});
    throw error;
  } finally {
    await client.end();
  }
}

/**
 * Drop a project schema and everything in it.
 *
 * This is the rollback half of `createProjectSchema`, safe only on a fresh,
 * empty schema — CASCADE is fine precisely because nothing has been written yet.
 * It is NOT the delete path: deleting a project soft-deletes the `ProjectMeta`
 * row and retains the schema for restore. The name is validated before it
 * reaches the quoted identifier.
 */
export async function dropProjectSchema(schemaName: string): Promise<void> {
  assertValidSchemaName(schemaName);

  const client = new Client({ connectionString: databaseUrl() });
  try {
    await client.connect();
    await client.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`);
  } finally {
    await client.end();
  }
}
